### PR TITLE
Velocity parsing : Added ConcurrentHashMap for caching the parsed nodes

### PR DESCRIPTION
**Pull request by meeximum**
In our case this brings a performance improvement!

### CODE REVIEW

**Comment by stariy95** [comment]
Hi @meeximum,

Thank you for your pull request, indeed caching can be helpful in query parsing.
But I see some problems with your solution:
1. Cache is unbound, so it can lead to memory leaks in long living apps.
2. SimpleNode is a mutable object, and even if it is used only inside parser, we shouldn't assume that it wouldn't change its state somehow.

So while this solution can be really helpful in certain Cayenne usage, we can't approve this for general usage.
Moreover the caching inside Cayenne probably should be redesigned, so this task is out of scope for 4.0 release as it is close to BETA stage.

Also I've created JIRA issue not to lose your idea: https://issues.apache.org/jira/browse/CAY-2247

**Comment by meeximum** [comment]
Hi,

thank for your feedback, maybe I should have used JCache ;-)
I'm looking forward for your redesigning indentions.

br
Meex

Nikita Timofeev <notifications@github.com> schrieb am Fr., 24. Feb. 2017 um
10:21 Uhr:

**Comment by ben-manes** [comment]
Cayenne is currently using concurrentlinkedhashmap for caching, so an option is available data structure wise. It's successor, Caffeine, has optional jcache support.

**Comment by stariy95** [comment]
For the history.
Per #238 Cayenne got own template parser with proper result caching.

**Pull request closed without merging**
