### PR TITLE
Added the ability to generate a primary key using sequences (since version MS SQL 2012) and 'NEWID()' in cayenne-server

### PR DESCRIPTION
**Pull request by PRIESt512**
If the type of the key is integer, uses the sequences.
If the key type is UNIQUEIDENTIFIER, uses the built-in function NEWID()

### CODE REVIEW

**Comment by andrus** [comment]
Thanks for the PR. Discussing it now on the dev list: https://lists.apache.org/list.html?dev@cayenne.apache.org The choices we have to make highlight the need for the adapter API refactoring.

**Comment by PRIESt512** [comment]
Hello! Made the choice of the key separately from the adapter. I tried to take into account the philosophy of Cayenne. While as a preview version. I will be glad to hear comments/suggestions. 

P.S. Thank you in advance for your product! I want to make it even better

**Comment by stariy95** [comment]
Thanks for your effort, it's very impressing!

Wanted to share some thoughts about your code.

While I like the idea to hide complexity from user in general, I think it is better to create some simpler solution at first and go from there. I don't feel it will be good to introduce some complex logic that will depend on exact `DbVersion`. Cayenne now have 12 DbAdapters and it can easily become unmanageable in the future.

So it may be better to start with simple per-adapter `PkGenerator` binding ([PerAdapterProvider<T>](https://github.com/apache/cayenne/blob/master/cayenne-server/src/main/java/org/apache/cayenne/dba/PerAdapterProvider.java) can help with that). And leave customization up to user (this is a general approach in Cayenne, as I see it)

I.e. we'll be able to use non-default (provided by Cayenne or by user) `PkGenerator` like this:
```
ServerRuntimeBuilder
    .addModule(binder -> 
        ServerModule.contributePkGenerators(binder)
            .put(SQLServerAdapter.class.getName(), SQLServerPkGenerator.class))
```

And there is also one technical aspect that should be taken into account. [Here](https://github.com/apache/cayenne/pull/277/files#diff-55d57dd56ccf4d7edb4ccf18f342e171R70) `AdhocObjectFactory` should be used to instantiate PkGenerator, otherwise OSGI-like environments can be broken. I believe this will require some PkGenerators refactoring, to enable default constructor.

**Comment by PRIESt512** [comment]
@stariy95  Good remarks! I'll make changes to the code! Originally I planned to do the `PkGenerator` using `AdhocObjectFactory`. However, I was not sure that I had the right to make such changes. Therefore I decided to choose the maximum compatibility with the old code. But I have a question, but how will the choice of a specific `PkGenerator` in the CayenneModeler occur then? Will you need to add new functionality? So I tried to make an automatic choice. If it is necessary, I will study the CayenneModeler code with interest and try to add a choice. Naturally this will be the next task.

Thanks for the help! :-)

**Comment by stariy95** [comment]
@PRIESt512 I think there is no need to add this feature to the Modeler, as we are moving all runtime-related parts out of it to, well, runtime :)

**Comment by PRIESt512** [comment]
Hi! Made the refactoring of the PK. Preliminary version. However, I think that you should add tests to check all PK's

**Comment by stariy95** [comment]
Hi @PRIESt512! Your code looks good to me, great job 👍 
Will you be able to refactor all other PK generators, or I'm asking too much? :)

**Comment by PRIESt512** [comment]
With great pleasure I will perform refactoring of other PK! I'll do it as soon as possible :)

**Comment by PRIESt512** [comment]
Hi @stariy95! Finished refactoring PKs. In the testing process, maybe I identified the old bug in a Derby:
`Caused by: ERROR X0Y84: Too much contention on sequence PK_TEST_QUALIFIED2. This is probably caused by an uncommitted scan of the SYS.SYSSEQUENCES catalog. Do not query this catalog directly. Instead, use the SYSCS_UTIL.SYSCS_PEEK_AT_SEQUENCE function to view the current value of a sequence generator.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.catalog.SequenceUpdater.tooMuchContentionException(Unknown Source)
	at org.apache.derby.impl.sql.catalog.SequenceUpdater.getCurrentValueAndAdvance(Unknown Source)
	at org.apache.derby.impl.sql.catalog.DataDictionaryImpl.getCurrentValueAndAdvance(Unknown Source)
	at org.apache.derby.impl.sql.execute.BaseActivation.getCurrentValueAndAdvance(Unknown Source)
	at org.apache.derby.exe.ac07afa414x0162x826dx42adx000006535bb8340.e0(Unknown Source)
	at org.apache.derby.impl.services.reflect.DirectCall.invoke(Unknown Source)
	at org.apache.derby.impl.sql.execute.RowResultSet.getNextRowCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.BasicNoPutResultSetImpl.getNextRow(Unknown Source)`

`Caused by: java.sql.SQLException: Too much contention on sequence PK_TEST_QUALIFIED2. This is probably caused by an uncommitted scan of the SYS.SYSSEQUENCES catalog. Do not query this catalog directly. Instead, use the SYSCS_UTIL.SYSCS_PEEK_AT_SEQUENCE function to view the current value of a sequence generator.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedResultSet.closeOnTransactionError(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedResultSet.movePosition(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedResultSet.next(Unknown Source)
	at org.apache.cayenne.dba.oracle.OraclePkGenerator.longPkFromDatabase(OraclePkGenerator.java:176)
	at org.apache.cayenne.dba.JdbcPkGenerator.generatePk(JdbcPkGenerator.java:232)
	at org.apache.cayenne.access.DataDomainInsertBucket.createPermIds(DataDomainInsertBucket.java:162)
	at org.apache.cayenne.access.DataDomainInsertBucket.appendQueriesInternal(DataDomainInsertBucket.java:73)
	at org.apache.cayenne.access.DataDomainSyncBucket.appendQueries(DataDomainSyncBucket.java:78)
	at org.apache.cayenne.access.DataDomainFlushAction.preprocess(DataDomainFlushAction.java:185)
	at org.apache.cayenne.access.DataDomainFlushAction.flush(DataDomainFlushAction.java:143)
	at org.apache.cayenne.access.DataDomain.onSyncFlush(DataDomain.java:621)
	at org.apache.cayenne.access.DataDomain.onSyncNoFilters(DataDomain.java:591)
	at org.apache.cayenne.access.DataDomain$DataDomainSyncFilterChain.onSync(DataDomain.java:752)
	at org.apache.cayenne.tx.TransactionFilter$1.perform(TransactionFilter.java:73)
	at org.apache.cayenne.tx.TransactionFilter$1.perform(TransactionFilter.java:70)`

This bug Affects Version: 10.8.2.2 Derby. It was fixed. As I understand in cayenne version Derby - 10.12.1.1. It is possible that this error reappeared in the Derby? Is it necessary to report this?

[ERROR X0Y84: Too much contention on sequence](https://issues.apache.org/jira/browse/DERBY-5423)

**Comment by stariy95** [comment]
@PRIESt512 thanks for such an impressive work! I'll try to review all your changes and provide feedback ASAP.

**Comment by stariy95** [comment]
Hi again @PRIESt512, I've got time to review. Found one thing that keeps me from applying this PR :)
I think that it would be better to move ``PkGenerator`` setup from adapter sniffers up to ``DefaultDbAdapterFactory``. 
Right now there is code path that bypass sniffers completely:

```java
if (adapterType != null) {
    // here we'll miss PkGenerator setup
    return objectFactory.newInstance(DbAdapter.class, adapterType);
} else {
    return new AutoAdapter(() -> detectAdapter(dataSource), jdbcEventLogger);
}
```

**Comment by PRIESt512** [comment]
Thanks for the review! I then change the code with your comments :)

**Comment by PRIESt512** [comment]
@stariy95 Hello! I finally reached the code. Is everything all right now?

**Comment by stariy95** [comment]
@PRIESt512 thanks for this fantastic job! I think it's time to merge this PR :)

**Comment by stariy95** [comment]
@PRIESt512 you can email me at ntimofeev at apache dot org

**Pull request merged**
