### PR TITLE
CaseWhen sqlBuilder API 

### PR DESCRIPTION
**Pull request by Ivan-nikitko**

### CODE REVIEW

**Comment by andrus** [comment]
@stariy95 , @Ivan-nikitko Hey guys, I don't see any references to Jira numbers or entries in the RELEASE-NOTES. How are we going to track all the new features if we do not link them to Jiras.

**Comment by stariy95** [comment]
This is part of the [CAY-2597](https://issues.apache.org/jira/browse/CAY-2597) but this PR doesn't bring any public changes.

**Comment by andrus** [comment]
Thanks for clarifying. I guess in such cases there's still a benefit to referencing Jira ID in Git comments, so that the commits can be attributed to a specific feature effort.

**Comment by andrus** [comment]
Oh, maybe also in CAY-2597 we can give a short description / examples of the future user-facing API? I am very curious how the new `when` will look from the user POV

**Comment by stariy95** [comment]
@andrus Public API for that is in progress now. Once we got something worth sharing I'll update JIRA issue.

**Pull request merged**
