### PR TITLE
Ordering chaining

### PR DESCRIPTION
**Pull request by lonvarscsak**
Hey all, I've got a commit (that I plan on using) that I think is useful.  I've added an Orderings class which is a subclass of ArrayList<Ordering>, and then added methods to allow chaining of multiple Ordering through Propertys.

So for example:

`Person.COMPANY_NAME.asc().then(Person.FIRST_NAME.desc())
`

Rather than typing:

`Arrays.asList(Person.COMPANY_NAME.asc(), Person.FIRST_NAME.desc())
`

You can chain together Ordering (into an Orderings) or Orderings into other Orderings.

`Person.COMPANY_NAME.asc().then(Person.LAST_NAME.asc()).then(Person.FIRST_NAME.asc())
`

I find it to be convenient and cleaner, but I'm used to this kind of thing in WOnder. :)

Thoughts?

### CODE REVIEW

**Comment by andrus** [comment]
Thanks for the PR. I am +0.

I wouldn't use this API for queries, as the alternative of attaching to the query directly is easier:
```java
ObjectSelect
     .query(Person.class)
    .orderBy(Person.COMPANY_NAME.asc(), Person.FIRST_NAME.desc());
```
Though I guess it may be useful for building in-memory ordering sequences. 

A few notes on the code:

* We need the Apache license header on the new OrderingsClass
* I wouldn't subclass ArrayList though. Rather hide it inside the Orderings class for cleaner encapsulation
* We need unit tests...

Anyone else has thoughts on this?

**Comment by andrus** [comment]
I took this discussion to the dev list to ensure everybody sees it:
https://lists.apache.org/thread.html/81091880b3e8a64302f5f3b1a67cd706b60f157c3ae48ccda4e8e0e4@%3Cdev.cayenne.apache.org%3E

My other consideration is Java 8 Comparator interface already has chaining functionality. So Orderings seems redundant now, isn't it?

**Comment by mrg** [comment]
I think the `orderBy(...)` syntax is easier and cleaner (at least to me), plus subclassing `ArrayList` feels a tad wrong to me since `ascs` returns a concrete implementation now instead of an interface.  Admittedly this is a personal opinion.  There are also Java 8 specific things (`Property<>` vs `Property<Object>`) which shouldn't be in cayenne-server.  I think I'd lean more towards a -1 on this one, but need to evaluate it more.

**Comment by lonvarscsak** [comment]
I get it, you all hate me…I understand. ;)

The ArrayList is to be compatible with other APIs that expect a List of
Ordering.  I’m curious why returning an implementation is really any
different than what ascs() does today.  I get that the user is hidden from
the implementation deal, but both return ArrayList.  I pretty much always
use SelectQuery which takes a List<Ordering>.

I didn’t realize I had Java 8 stuff in there, that’s my mistake, I’d
correct if this was going any further. :P

The Java 8 Comparator stuff I hadn’t considered (since Cayenne is not Java
8), but you’re right, that might work just fine.  I’ll give that a whirl
and see if it meets my needs.

-Lon

**Comment by lonvarscsak** [comment]
Closed for little interest.

**Pull request closed without merging**
