### PR TITLE
CAY-2650 Support using generated primary keys along with batch inserts

### PR DESCRIPTION
**Pull request by johnthuss**

### CODE REVIEW

**Comment by stariy95** [comment]
Hi @johnthuss,
It's really great you implemented this. IIRC someone mentioned having problems without PK generation batching. 
Just in case, have you seen that Derby and SQLServer tests are failing?

**Comment by johnthuss** [comment]
Yeah, I was the one who mentioned the problem.  :-)
I was planning to check back to see the test results, but hadn't yet. So thanks for the heads up.
I can test derby on my own machine, but I don't have a docker setup for SQLServer. Is anyone else able to address that DB?

**Comment by johnthuss** [comment]
It seems Derby does not support multi-row generated keys.

From https://issues.apache.org/jira/browse/DERBY-3609

> Statement.getGeneratedKeys() is partially implemented, and behaves very similar to IDENTITY_VAL_LOCAL() since it will only return a meaningful result when an single row insert is done with INSERT...VALUES.
> 
> The correct behavior (if DatabaseMetaData.supportsGetGeneratedKeys() returns true) is defined in the JDBC3 spec, section 13.6 (Retrieving Auto Generated Keys).
> 
> It requires support for multirow inserts, namely
> "In some cases, such as in an insert select statement, more than one key may be
> returned. The ResultSet object returned by getGeneratedKeys will contain a
> row for each key that a statement generated. If no keys are generated, an empty
> result set will be returned."

So the driver is sort of lying when it says that it supports generated keys. Should I introduce a new flag into JdbcAdapter like "supportsGeneratedKeysInBatchInserts"?

**Comment by johnthuss** [comment]
SQL Server does not support this either.
https://github.com/microsoft/mssql-jdbc/issues/245

They say the spec makes it optional.

> On JDBC specification it says
> > It is implementation-defined as to whether getGeneratedKeys will return generated values after invoking the executeBatch method.

**Comment by andrus** [comment]
So the fact that this is supported only by some DBs means we need a way to choose the strategy based on the adapter config.

**Comment by johnthuss** [comment]
The postgres build is failing to start up due to a build server issue.

**Comment by stariy95** [comment]
FYI I've pushed a fix for the postgres build, I think it was a change in a Postgres docker image.

**Comment by johnthuss** [comment]
Thanks. It build successfully now (I guess without the docker change).

**Pull request merged**
