### PR TITLE
Applying new Reverse Engineering to the Modeler

### PR DESCRIPTION
**Pull request by ollybondareva**

### CODE REVIEW

**Comment by andrus** [comment]
I just tried running the modeler with these changes. I like how the new UI for reverse engineering looks. However I wasn't able to reengineer my test MySQL DB. When I tweak reengineering XML and click "execute", nothing happens. Is this still something we need to finish?

**Comment by thinline72** [comment]
We need to review code and make some tests. Also we have some things to discuss with Alex. So I think it is not the final commits. But hope we are close. We are applying it on the next week.

Anyway, looks strange that it doesn't work :( 
We will investigate and fix it.

**Comment by ollybondareva** [comment]
Andrus; please, check now if it is working ok or not. The bug was fixed, I think.

**Comment by dzmitryk** [comment]
@ollybondareva, thanks. I have merged these commits with several code formatting improvements. You can close this pull request now.

**Pull request closed without merging**
