### PR TITLE
CAY-2139 Upgrade HSQLDB dependency to latest version (2.3.4)

### PR DESCRIPTION
**Pull request by hugith**

### CODE REVIEW

**Comment by thinline72** [comment]
Hi @hugith,
Thank you for the pull-request.

Have you tried to build Cayenne via `mvn clean install` with these changes? The build freezes at this point for me:

```
[main] INFO org.apache.cayenne.datasource.DriverDataSource - Connecting to 'jdbc:hsqldb:mem:aname' as 'sa'
[main] INFO org.apache.cayenne.datasource.DriverDataSource - +++ Connecting: SUCCESS.
[main] INFO org.apache.cayenne.datasource.DriverDataSource - Connecting to 'jdbc:hsqldb:mem:aname' as 'sa'
[main] INFO org.apache.cayenne.datasource.DriverDataSource - +++ Connecting: SUCCESS.
[main] INFO org.apache.cayenne.configuration.XMLDataChannelDescriptorLoader - Loading XML configuration resource from file:/Users/skolbachev/Work/Cayenne/cayenne/cayenne-server/target/test-classes/cayenne-multinode.xml
[main] INFO org.apache.cayenne.configuration.XMLDataChannelDescriptorLoader - Loading XML DataMap resource from file:/Users/skolbachev/Work/Cayenne/cayenne/cayenne-server/target/test-classes/map-db1.map.xml
[main] INFO org.apache.cayenne.configuration.XMLDataChannelDescriptorLoader - Loading XML DataMap resource from file:/Users/skolbachev/Work/Cayenne/cayenne/cayenne-server/target/test-classes/map-db2.map.xml
[main] INFO org.apache.cayenne.test.jdbc.UtilityLogger - delete from CROSSDB_M1E1
[main] INFO org.apache.cayenne.test.jdbc.UtilityLogger - delete from CROSSDB_M2E2
[main] INFO org.apache.cayenne.test.jdbc.UtilityLogger - delete from CROSSDB_M2E1
[main] INFO org.apache.cayenne.log.CommonsJdbcEventLogger - --- transaction started.
[main] INFO org.apache.cayenne.log.CommonsJdbcEventLogger - SELECT NEXT_ID FROM AUTO_PK_SUPPORT WHERE TABLE_NAME = 'CROSSDB_M1E1'
[main] INFO org.apache.cayenne.log.CommonsJdbcEventLogger - === returned 1 row. - took 0 ms.
[main] INFO org.apache.cayenne.log.CommonsJdbcEventLogger - UPDATE AUTO_PK_SUPPORT SET NEXT_ID = NEXT_ID + 20 WHERE TABLE_NAME = 'CROSSDB_M1E1'
[main] INFO org.apache.cayenne.log.CommonsJdbcEventLogger - === updated 1 row.
[main] INFO org.apache.cayenne.log.CommonsJdbcEventLogger - SELECT NEXT_ID FROM AUTO_PK_SUPPORT WHERE TABLE_NAME = 'CROSSDB_M2E1'
```

**Comment by hugith** [comment]
Oh darn… I though all the tests were run as part of package, hadn't tried install. Sorry about that, I'll try to find out what's happening.

**Comment by andrus** [comment]
The tests are split into "unit" and "integration" (those with IT suffix). ```mvn test|package``` execute unit tests, while ```mvn verify|install``` execute both unit and integration.

**Comment by stariy95** [comment]
Hello @hugith!
I've made new pull request for HSQLDB version upgrade (#166) so this one can be closed I think.
Thank you for your changes I've used them :)

**Comment by hugith** [comment]
Awesome, thank you :)

**Pull request closed without merging**
